lab5/MichalKurpinskiLab5/DawidKobierskiLab5/Models/EFDbContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace DawidKobierskiLab5.Models
{
    public class EFDbContext : DbContext
    {
        public DbSet<Pizza> Pizzas { get; set; }
        public DbSet<Order> Orders { get; set; }

    }
}

lab5/MichalKurpinskiLab5/DawidKobierskiLab5/Models/Order.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc.Html;

namespace DawidKobierskiLab5.Models
{
    public  class Order
    {
        public int Id { get; set; }
        [Display(Name="Imię")]
        public string UserName { get; set; }
        [Display(Name = "Adres")]
        public string UserAdress { get; set; }
        public string Pizzas { get; set; }

        public Order(string pizzas)
        {
            Pizzas = pizzas;
        }

        public Order() { }
    }
}

lab5/MichalKurpinskiLab5/DawidKobierskiLab5/Models/Pizza.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using System.Web;

namespace DawidKobierskiLab5.Models
{
    public class Pizza
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public string Ingredients { get; set; }
        public bool IsOrdered { get; set; }

        public Pizza()
        {
            IsOrdered = false;
        }

    }
}

lab5/MichalKurpinskiLab5/DawidKobierskiLab5/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DawidKobierskiLab5.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

lab5/MichalKurpinskiLab5/DawidKobierskiLab5/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DawidKobierskiLab5.Models;

namespace DawidKobierskiLab5.Controllers
{
    public class OrderController : Controller
    {
        // GET: Order
        public ActionResult Index()
        {
            return RedirectToAction("Index", "Home");
        }
        /// <summary>
        /// Potwierdza zamówienie pizz bedacych w koszyku
        /// </summary>
        /// <returns></returns>
        public ActionResult Confirm()
        {
            return View(new Order());
        }

        [HttpPost]
        public ActionResult Confirm(Order order)
        {

            using (var ctx = new EFDbContext())
            {
                if (!ModelState.IsValid)
                {
                    return View(new Order());
                }
                var pizzas = "";
                foreach (var pizza in ctx.Pizzas.Where(x=>x.IsOrdered==true).ToList())
                {
                    pizzas += pizza.Name + ",";
                }
                order.Pizzas = pizzas;
                ctx.Orders.Add(order);
                foreach (var pizza in ctx.Pizzas.Where(x => x.IsOrdered == true).ToList())
                {
                    pizza.IsOrdered = false;
                }
                ctx.SaveChanges();
            }
            return RedirectToAction("OK");
        }
        /// <summary>
        /// wyswietla widok potwierdzajacy dokonanie zamówienia.
        /// </summary>
        /// <returns></returns>
        public ActionResult OK()
        {
            return View();
        }
        /// <summary>
        /// Zwraca listę wszystkich zamówien do widoku Zamówien(wyswietlenie zamowien)
        /// </summary>
        /// <returns></returns>
        public ActionResult Purchased()
        {
            List<Order> orders;
            using (var ctx = new EFDbContext())
            {
                orders = ctx.Orders.ToList();
            }
            return View(orders);
        }
        /// <summary>
        /// usuwa wybrane zamówienie z listy.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Delivered(int id)
        {
            Order order;
            using (var ctx = new EFDbContext())
            {
                order = ctx.Orders.Find(id);
                ctx.Orders.Remove(order);
                ctx.SaveChanges();
            }
            return RedirectToAction("Purchased");
        }
    }
}

lab5/MichalKurpinskiLab5/DawidKobierskiLab5/Controllers/PizzaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DawidKobierskiLab5.Models;

namespace DawidKobierskiLab5.Controllers
{
    public class PizzaController : Controller
    {
        // GET: Pizza
        public ActionResult Index()
        {
            return RedirectToAction("List");
        }
        /// <summary>
        /// Zwraca listę pizz do widoku Menu.
        /// </summary>
        /// <returns></returns>
        public ActionResult List()
        {
            List<Pizza> pizzas;

            using (var ctx = new EFDbContext())
            {
                pizzas = ctx.Pizzas.ToList();
            }
            return View(pizzas);
        }
        /// <summary>
        /// Dodaje pizzę do Menu.
        /// </summary>
        /// <returns></returns>
        public ActionResult Add()
        {
            return View(new Pizza());
        }

        [HttpPost]
        public ActionResult Add(Pizza pizza)
        {
            if (!ModelState.IsValid)
            {
                return View(new Pizza());
            }
            using (var ctx = new EFDbContext())
            {
                ctx.Pizzas.Add(pizza);
                ctx.SaveChanges();
            }

            return RedirectToAction("List");
        }

        /// <summary>
        /// Edytuje wybraną pizzę z menu.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Edit(int id)
        {
            Pizza pizza;
            using (var ctx = new EFDbContext())
            {
                pizza = ctx.Pizzas.FirstOrDefault(p => p.Id == id);
            }
            return View(pizza);
        }

        [HttpPost]
        public ActionResult Edit(Pizza model, int id)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Edit");
            }
            Pizza pizza;
            using (var ctx = new EFDbContext())
            {
                pizza = ctx.Pizzas.FirstOrDefault(p => p.Id == id);
                pizza.Name = model.Name;
                pizza.Ingredients = model.Ingredients;
                ctx.SaveChanges();
            }
            return RedirectToAction("List");
        }
        /// <summary>
        /// usuwa wybraną pizze z menu.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Delete(int id)
        {
            Pizza pizza;
            using (var ctx = new EFDbContext())
            {
                pizza = ctx.Pizzas.Find(id);
                ctx.Pizzas.Remove(pizza);
                ctx.SaveChanges();
            }
            return RedirectToAction("List");
        }
        /// <summary>
        /// Dodaje wybraną pizzę do koszyka.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Order(int id)
        {
            Pizza pizza;
            List<Pizza> pizzas;
            using (var ctx = new EFDbContext())
            {
                ctx.Pizzas.Find(id).IsOrdered = true;
                pizza = ctx.Pizzas.Find(id);
                pizzas = ctx.Pizzas.Where(x => x.IsOrdered == true).ToList();
                pizzas.Add(pizza);
                ctx.SaveChanges();
            }
            return RedirectToAction("List");
        }
        /// <summary>
        /// Zwraca listę pizz do widoku koszyka.
        /// </summary>
        /// <returns></returns>
        public ActionResult Orders()
        {
            List<Pizza> pizzas;
            using (var ctx = new EFDbContext())
            {
                pizzas = ctx.Pizzas.Where(x => x.IsOrdered == true).ToList();
            }
            return View(pizzas);
        }
        /// <summary>
        /// usuwa wybrana pizze z koszyka.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Cancel(int id)
        {

            using (var ctx = new EFDbContext())
            {
                ctx.Pizzas.Find(id).IsOrdered = false;
                ctx.SaveChanges();
            }
            return RedirectToAction("Orders");
        }
    }
}

lab5/MichalKurpinskiLab5/DawidKobierskiLab5/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Pizza Store";
}
<div class="page-header">
    <h1 style="font-size: 40px; font-family: fantasy;letter-spacing: 3px">Strona główna</h1>
    <br/><br/><br/>
    <div><img src="https://pbs.twimg.com/media/CRWnAdOWwAA9c5Q.jpg" alt="" style="float: right;"/>
        <p style="color: red; font-size: 25px;font-family: fantasy">
            <br/><br/><br/><br/>
            Tylko dzisiaj taka niepowtarzalna okazja!
        </p>
    </div>
    <div><img src="http://www.blog.travelstore.pl/wp-content/uploads/2015/09/wlochy.png" alt="" style="float: left;padding-top: 20px"/>
        <p style="color: blue; font-size: 25px; font-family: fantasy;">
            <br/><br/><br/><br/><br/><br/><br/>
            Poczuj się jak we włoskiej restauracji!
        </p>
    </div>
</div>
        

lab5/MichalKurpinskiLab5/DawidKobierskiLab5/Views/Order/Confirm.cshtml
@model DawidKobierskiLab5.Models.Order
@{
    ViewBag.Title = "Dodaj Zamówienie";
}

<h2>Dodaj Zamówienie</h2>

@using (Html.BeginForm())
{
    @Html.HiddenFor(m => m.Id)

    <div class="form-group">
        @Html.LabelFor(m => m.UserName)
        @Html.TextBoxFor(m => m.UserName, new { @class = "form-control"})
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.UserAdress)
        @Html.TextBoxFor(m => m.UserAdress, new {@class = "form-control"})
    </div>
    <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-saved"></span> Kup</button>
}

lab5/MichalKurpinskiLab5/DawidKobierskiLab5/Views/Order/OK.cshtml
@{
    ViewBag.Title = "Zamowienie przyjęte";
}

<h2>Zamówienie przyjęte.:) Nasza pizza niedługo do Ciebie zawita, przygotuj się.</h2>
<p style="font-size: 40; color: blue"></p>
@Html.ActionLink("Wróc do Strony Głownej","Index","Home",null,new { @class = "btn btn-success"})

lab5/MichalKurpinskiLab5/DawidKobierskiLab5/Views/Order/Purchased.cshtml
@using DawidKobierskiLab5.Models
@model List<DawidKobierskiLab5.Models.Order>
@{
    ViewBag.Title = "Zamówienia";
}
@{ string pizzas = "";}
<h2>Zamówienia</h2>

<table class="table table-bordered table-striped" style="background: white">
    <thead>
    <tr>
        <th>Lp.</th>
        <th>Zamawiający</th>
        <th>Adres</th>
        <th>Pizze</th>
        <th>Akcje</th>
    </tr>
    <tbody>
        @foreach (var order in Model)
        {
            <tr>
                <td>@order.Id</td>
                <td>@order.UserName</td>
                <td>@order.UserAdress</td>
                <td>@order.Pizzas</td>
                <td>@Html.ActionLink("Dostarczone", "Delivered", new {id = order.Id}, new {@class = "btn btn-danger"})</td>

            </tr>
        }
    </tbody>
    </thead>

</table>

lab5/MichalKurpinskiLab5/DawidKobierskiLab5/Views/Pizza/Add.cshtml
@model DawidKobierskiLab5.Models.Pizza

@{
    ViewBag.Title = "Dodaj pizze";
}

<h2>Dodaj pizze</h2>

@using (Html.BeginForm())
{
    @Html.HiddenFor(m => m.Id)

    <div class="form-group">
        @Html.LabelFor(m => m.Name)
        @Html.TextBoxFor(m => m.Name, new { @class = "form-control"})
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Ingredients)
        @Html.TextBoxFor(m => m.Ingredients, new { @class = "form-control"})
    </div>

    <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-saved"></span> Dodaj</button>
}

lab5/MichalKurpinskiLab5/DawidKobierskiLab5/Views/Pizza/Edit.cshtml
@model DawidKobierskiLab5.Models.Pizza

@{
    ViewBag.Title = "Edytuj";
}

<h2>Edytuj</h2>

@using (Html.BeginForm())
{
    @Html.HiddenFor(m => m.Id)

    <div class="form-group">
        @Html.LabelFor(m => m.Name)
        @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Ingredients)
        @Html.TextBoxFor(m => m.Ingredients, new { @class = "form-control" })
    </div>

    <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-saved"></span> Edytuj</button>
}

lab5/MichalKurpinskiLab5/DawidKobierskiLab5/Views/Pizza/List.cshtml
        @using System.Web.UI.WebControls        @model System.Collections.Generic.List<DawidKobierskiLab5.Models.Pizza>
@{
    ViewBag.Title = "Menu";
}

<h2>Menu</h2>

@Html.ActionLink("Dodaj pizze","Add",null,new { @class = "btn btn-success"})

<table class="table table-bordered table-striped" style="background: white">
    <thead>
    <tr>
        <th>Lp.</th>
        <th>Nazwa</th>
        <th>Składniki</th>
        <th>Akcje</th>
    </tr>
    <tbody>
        @foreach (var pizza in Model)
        {

            <tr>
                <td>@pizza.Id</td>
                <td>@pizza.Name</td>
                <td>@pizza.Ingredients</td>
                <td>@Html.ActionLink("Zamów", "Order", new { id = pizza.Id }, new { @class = "btn btn-success" })</td>
                <td>@Html.ActionLink("Edytuj", "Edit", new {id = pizza.Id}, new {@class = "btn btn-primary"})</td>
                <td>@Html.ActionLink("Usuń", "Delete", new {id = pizza.Id}, new {@class = "btn btn-danger"})</td>

            </tr>
        }
    </tbody>
    </thead>

</table>

lab5/MichalKurpinskiLab5/DawidKobierskiLab5/Views/Pizza/Orders.cshtml
@model System.Collections.Generic.List<DawidKobierskiLab5.Models.Pizza>

@{
    ViewBag.Title = "Koszyk";
}

<h2>Koszyk</h2>

@if (Model.Count == 0)
{
    <div>
        <img src="https://image.freepik.com/darmowe-wektory/pusty-koszyk-w-3d_72147488628.jpg" alt="" style="float: left; padding-top: 20px"/>
        <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
        <p style="color: red; font-size: large; text-decoration: none; font-family: fantasy; font-size: 30px">Twój koszyk jest pusty, zamów coś:)</p>
    </div>
}
else
{

    <table class="table table-bordered table-striped" style="background: white">
        <thead>
        <tr>
            <th>Lp.</th>
            <th>Nazwa</th>
            <th>Składniki</th>
            <th>Akcje</th>
        </tr>
        <tbody>
        @foreach (var pizza in Model)
        {

            <tr>
                <td>@pizza.Id</td>
                <td>@pizza.Name</td>
                <td>@pizza.Ingredients</td>
                <td>@Html.ActionLink("Anuluj", "Cancel", new {id = pizza.Id}, new {@class = "btn btn-danger"})</td>

            </tr>
        }
        </tbody>
        </thead>

    </table>
    <p style="text-align: right">
        @Html.ActionLink("Potwierdz zamowienie", "Confirm", "Order", null, new {@class = "btn btn-success"})</p>
    
        
}

lab5/MichalKurpinskiLab5/DawidKobierskiLab5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pizza Store - @ViewBag.Title</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css"/>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css"/>
    <script src="~/Scripts/modernizr-2.6.2.js"></script>


</head>
<body style="background-color: wheat">
<div class="navbar  navbar-fixed-top" style="background:skyblue ; font-size: 20px; font-family: fantasy;">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" style="font-family: fantasy; font-size: 30px">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Pizza Store", "Index", "Home", new {area = ""}, new {@class = "navbar-brand"})
        </div>
        <div class="navbar-">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Menu", "List", "Pizza")</li>
            </ul>
        </div>
        <div class="navbar-">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Wszystkie Zamówienia", "Purchased", "Order")</li>
            </ul>
        </div>
        <div class="navbar-">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Koszyk", "Orders", "Pizza")</li>
            </ul>
        </div>

    </div>
</div>

<div class="container body-content">
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year - Pizza Store</p>
    </footer>
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>